### ISSUE TITLE
mmcv version problem

### ISSUE THREAD

**Issue by taewookum** [zxcqlf/MonoViT#12]
The following error occurs due to the mmcv version problem, how did you solve it?

ModuleNotFoundError: No module named 'mmcv._ext'

**Comment by zxcqlf** [comment]
Did you finish the installation of the mmcv? Note that it will take a long time to fully install, please make sure that it has been completely installed.

**Comment by taewookum** [comment]
I installed it with mmcv full==1.3.0, but it doesn't seem to be installing. 

Initially, I installed cudatoolkit=11.1.1 and cudn=8.1.0.77 and copied the environmental installation code you shared. But it says mmcv._ext is missing.

**Comment by zxcqlf** [comment]
Please follow the version of each package suggested in the github:
pip3 install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0
pip3 install mmcv-full==1.3.0 mmsegmentation==0.11.0  
For the problem of envs, please ask google for help, because different systems and hardware have different characteristics.
